# Generated by Django 4.2.29 on 2026-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upi_pin',
            field=models.CharField(default='1234', max_length=4),
        ),
    ]
