# Generated by Django 6.0.3 on 2026-04-11 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_upi_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='borrowed_from_next_cycle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget_cycle_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_city',
            field=models.CharField(default='Pune', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='spent_this_cycle',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='advisory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='decision',
            field=models.CharField(default='approved_silent', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='explanations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('BLOCKED', 'Blocked')], default='SUCCESS', max_length=20),
        ),
    ]
