# Generated by Django 6.0.3 on 2026-04-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_borrowed_from_next_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='budget_cycle',
            field=models.CharField(default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='savings_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
