# Generated by Django 6.0.3 on 2026-04-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_goal_priority_goal_target_date_profile_budget_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
